### ISSUE TITLE
Conversion must require Cuda-Capabilities?

### ISSUE THREAD

**Issue by msclock** [triton-inference-server/model_navigator#22]
I have the configuration:
```txt
#!/usr/bin/env python3

import logging
import pathlib
from typing import Iterable
import math

import numpy as np
import model_navigator as nav
from model_navigator.api.config import Sample

LOGGER = logging.getLogger(__name__)


def get_model(FLAGS):
    model = pathlib.Path(FLAGS.input_model)
    if model.suffix == ".pt":
        from yolov5_utils.yolov5 import export

        export.run(
            weights=FLAGS.input_model,
            imgsz=(FLAGS.img, FLAGS.img),
            dynamic=True,
            device=FLAGS.device,
        )
    return model.with_suffix(".onnx")


def get_dataloader(FLAGS):
    return [
        np.random.randn(1, 3, FLAGS.img, FLAGS.img).astype(np.float32)
        for _ in range(FLAGS.batch_size)
    ]


def get_verify_function():
    def verify_func(ys_runner: Iterable[Sample], ys_expected: Iterable[Sample]) -> bool:
        for y_runner, y_expected in zip(ys_runner, ys_expected):
            if not all(
                np.allclose(a, b, rtol=1.0e-3, atol=1.0e-3)
                for a, b in zip(y_runner.values(), y_expected.values())
            ):
                return False
        return True

    return verify_func


def get_profiler_config(FLAGS):
    return nav.onnx.ProfilerConfig(
        run_profiling=True,
        batch_sizes=[
            1,
            math.ceil(FLAGS.batch_size / 2),
            FLAGS.batch_size,
        ],
        measurement_mode=nav.MeasurementMode.TIME_WINDOWS,
        measurement_interval=2500,  # ms
        measurement_request_count=10,
        stability_percentage=15,
        max_trials=5,
        throughput_cutoff_threshold=0.1,
    )


def get_configuration(FLAGS):
    return {
        "custom_configs": [
            nav.TensorRTConfig(
                precision=(nav.TensorRTPrecision.FP32),
                max_workspace_size=4 * 1024 * 1024 * 1024,  # 4GB
                trt_profile=nav.TensorRTProfile().add(
                    "images",
                    (1, 3, FLAGS.img, FLAGS.img),
                    (
                        math.ceil(FLAGS.batch_size / 2),
                        3,
                        FLAGS.img,
                        FLAGS.img,
                    ),
                    (FLAGS.batch_size, 3, FLAGS.img, FLAGS.img),
                ),
            ),
            nav.OnnxConfig(opset=17),
        ]
    }


def parse_args():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--workspace",
        type=str,
        default=".navigator_workspace",
        help="navigator cache workspace",
    )
    parser.add_argument(
        "--input-model",
        type=str,
        default="yolov5m.pt",
        help="input model",
    )
    parser.add_argument(
        "--model-name",
        type=str,
        default="yolov5",
        help="sub dir model name in model store model_repository folder",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=4,
        help="batch size on model",
    )
    parser.add_argument(
        "--img",
        type=int,
        default=1280,
        help="image size",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="device = None or 'cpu' or 0 or '0' or '0,1,2,3'",
    )
    parser.add_argument(
        "--min-top1-accuracy",
        type=float,
        default=0.9,
    )
    parser.add_argument(
        "--model-repository",
        type=str,
        default=f".model_repository",
        help="model repository folder serving on tirton",
    )
    return parser.parse_args()


def main(FLAGS):
    model = get_model(FLAGS)
    dataloader = get_dataloader(FLAGS)
    verify_func = get_verify_function()
    configuration = get_configuration(FLAGS)
    profiler_config = get_profiler_config(FLAGS)

    package = nav.onnx.optimize(
        model=model,
        dataloader=dataloader,
        # target_formats=(nav.Format.TENSORRT),
        verify_func=verify_func,
        target_device=nav.DeviceKind.CPU,
        profiler_config=profiler_config,
        debug=True,
        verbose=True,
        workspace=pathlib.Path(FLAGS.workspace) / FLAGS.model_name,
        # **configuration,
    )

    import shutil

    shutil.rmtree(
        pathlib.Path(FLAGS.model_repository) / FLAGS.model_name,
        ignore_errors=True,
    )
    nav.triton.model_repository.add_model_from_package(
        model_repository_path=pathlib.Path(FLAGS.model_repository),
        model_name=FLAGS.model_name,
        package=package,
        strategy=nav.MaxThroughputStrategy(),
    )


if __name__ == "__main__":
    main(parse_args())

```

When I do:
```bash
pip install -U --extra-index-url https://pypi.ngc.nvidia.com triton-model-navigator

./optimize_onnx.py --input-model=yolov5m.pt \
    --model-name=yolov5 \
    --batch-size=4 \
    --device=0 \
    --model-repository=./model_repository
```
I got the error  with the lack of Cuda-capable device is detected:
```txt
YOLOv5 🚀 2023-6-19 Python-3.8.10 torch-1.14.0a0+410ce96 CPU

Fusing layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients

PyTorch: starting from yolov5m.pt with output shape (1, 100800, 85) (40.8 MB)

TorchScript: starting export with torch 1.14.0a0+410ce96...
TorchScript: export success ✅ 8.1s, saved as yolov5m.torchscript (81.2 MB)

ONNX: starting export with onnx 1.12.0...
ONNX: export success ✅ 2.6s, saved as yolov5m.onnx (80.8 MB)

Export complete (14.1s)
Results saved to /workspaces/ai-serving-solution/deploy/triton_model_utils/example/yolov5
Detect:          python detect.py --weights yolov5m.onnx 
Validate:        python val.py --weights yolov5m.onnx 
PyTorch Hub:     model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5m.onnx')  
Visualize:       https://netron.app
2023-06-21 10:58:09 INFO     Navigator: ============================== Common config parameters ============================================
2023-06-21 10:58:09 INFO     Navigator: {
    "framework": "onnx",
    "workspace": ".navigator_workspace/yolov5",
    "target_formats": [
        "onnx",
        "trt"
    ],
    "target_device": "cpu",
    "sample_count": 100,
    "profiler_config": {
        "run_profiling": true,
        "batch_sizes": [
            1,
            2,
            4
        ],
        "measurement_mode": "time_windows",
        "measurement_interval": 2500,
        "measurement_request_count": 10,
        "stability_percentage": 15,
        "max_trials": 5,
        "throughput_cutoff_threshold": 0.1
    },
    "runner_names": [
        "TensorFlowSavedModelCPU",
        "TensorFlowCPU",
        "OnnxCPU",
        "TorchScriptCPU",
        "TorchCPU",
        "PythonRunner"
    ],
    "batch_dim": 0,
    "seed": 0,
    "_input_names": null,
    "_output_names": null,
    "from_source": true,
    "forward_kw_names": null,
    "custom_configs": {},
    "verbose": true,
    "debug": true
}
2023-06-21 10:58:11 INFO     Navigator: Removing exiting workspace at .navigator_workspace/yolov5
2023-06-21 10:58:11 INFO     Navigator: ============================== Pipeline 'Preprocessing' started ====================================
2023-06-21 10:58:11 INFO     Navigator: ============================== Command 'InferInputMetadata' started ================================
2023-06-21 10:58:11 ERROR    Navigator: Command finished with unexpected error: Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/pipelines/pipeline.py", line 111, in _execute_unit
    command_output = execution_unit.command(status).run(
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/commands/base.py", line 78, in run
    output = self._run(*args, **_filter_dict_for_func(kwargs, self._run))
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/commands/infer_metadata.py", line 128, in _run
    input_names = self._get_default_input_names(model, sample, framework)
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/commands/infer_metadata.py", line 160, in _get_default_input_names
    onnxrt_runner_cls = OnnxrtCUDARunner if is_cuda_available() else OnnxrtCPURunner
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/utils/devices.py", line 127, in is_cuda_available
    return bool(get_gpus(["all"]))
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/utils/devices.py", line 79, in get_gpus
    devices = [dev["uuid"] for dev in get_available_gpus()]
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/utils/devices.py", line 54, in get_available_gpus
    _check_ret(cuda.cuInit(0))
  File "/home/vscode/.local/lib/python3.8/site-packages/model_navigator/utils/devices.py", line 40, in _check_ret
    raise ModelNavigatorError(f"CUDA error: {err_str.value}.")
model_navigator.exceptions.ModelNavigatorError: CUDA error: b'no CUDA-capable device is detected'.

The required command has failed. Please, review the log and verify the reported problems.
```

On the contrary, I execute the command with my cuda device 0, and everything is OK:
```bash
./optimize_onnx.py --device=0
```

**Comment by msclock** [comment]
I finally found the codes:https://github.com/triton-inference-server/model_navigator/blob/abadd6c80acdb27636eb84bb2dc6ab8eb6f8716a/model_navigator/utils/devices.py#L36-L67

```python
_check_ret(cuda.cuInit(0)) 
```
The above line assert a cuda device 0 must exist. So it does requre the existence of cuda device ?

**Comment by msclock** [comment]
Hi, I found the problem. That's my export code set `os.environ['CUDA_VISIBLE_DEVICES'] = '-1'  # force torch.cuda.is_available() = False` to disable cuda.
